require "yard" unless defined?(YARD)

desc "noop task that is used by other tasks"

YARD::Rake::YardocTask.new(:yard_for_generate_documentation) do |task|
  util_files = %w{
    architecture
    cloud
    introspection
    os
    platform
    platform_family
    platform_version
    service
    virtualization
    which
    windows
  }

  task.files = ["vendor/ruby/**/bundler/gems/chef*/chef-utils/lib/chef-utils/dsl/{#{util_files.join(',')}}.rb"]

  dsl_files = %w{
    chef_vault
    declare_resource
  }

  task.files.concat(["vendor/ruby/**/bundler/gems/chef*/lib/chef/dsl/{#{dsl_files.join(',')}}.rb"])
  task.options = ["--no-output"]
end

desc "Generate vscode snippets for chef-utils helpers"

def install_gem_utils
  require "bundler"

  Bundler.with_clean_env do
    sh "bundle config --local path 'vendor'"
    sh "bundle install"
    sh "bundle update"
  end
end

task :generate_snippets do
  Encoding.default_external = Encoding::UTF_8

  # make sure we have chef-utils files locally for yard inspection
  install_gem_utils

  require "fileutils" unless defined?(FileUtils)
  require "json" unless defined?(JSON)

  Rake::Task[:yard_for_generate_documentation].execute

  doc_data = {}

  YARD::Registry.load!

  YARD::Registry.all(:method).to_a.each do |obj|
    # we don't want to document all the chef-sugar backwards compat aliases
    # We can't use .is_alias? here since it fired on the original methods as well
    next if obj.docstring.match?(/chef-sugar backcompat method/)

    # we don't want private API methods
    next unless obj.visibility == :public

    doc_data[obj.name.to_s] = {}
    doc_data[obj.name.to_s]["prefix"] = obj.name.to_s
    doc_data[obj.name.to_s]["body"] = obj.name.to_s
    doc_data[obj.name.to_s]["description"] = obj.docstring
    doc_data[obj.name.to_s]["scope"] = "source.ruby.chef"

    unless doc_data[obj.name.to_s]["description"].end_with?('.')
      doc_data[obj.name.to_s]["description"] << '.'
    end

    if obj.has_tag?('since')
      doc_data[obj.name.to_s]["description"] << " Introduced in Chef Infra Client #{obj.tag('since').text}."
    end
  end

  File.open("../snippets/automated_dsl_snippets.json", "w") do |f|
    f.write(JSON.pretty_generate(doc_data.sort.to_h))
  end
end

task default: :generate_snippets
