---
  name: ci

  on:
    pull_request:

  jobs:
    validate:
      runs-on: ubuntu-latest

      steps:
        - name: Check out code
          uses: actions/checkout@v4
        - name: Validate snippet JSON files
          run: |
            for json in `ls snippets/*.json`
            do
              (cat ${json} | jq empty) || (echo "JSON parsing problem with ${json}" && exit 1)
            done

    build:
      needs: [validate]
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [20.x]
      steps:
        - uses: actions/checkout@v4
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}
        - run: npm ci
        - run: npx vsce package
